# Generated by Django 5.2.1 on 2025-06-02 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0004_alter_document_status"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_date",
                    models.DateField(auto_now_add=True, verbose_name="дата оплаты"),
                ),
                ("payment_amount", models.FloatField(verbose_name="сумма оплаты")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "оплата наличными"),
                            ("payment_transfer", "оплата переводом"),
                        ],
                        max_length=16,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, null=True, verbose_name="ссылка для оплаты"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, null=True, verbose_name="идентификатор оплаты"
                    ),
                ),
                (
                    "paid_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_document",
                        to="Documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплата",
            },
        ),
    ]
