services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    command: >
      sh -c 
      "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/app/staticfiles/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static_volume:/app/staticfiles/
    depends_on:
      - web

  celery_worker:
    build: .
    command: bash -c "cd /code && celery -A config worker --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web

  redis:
    image: redis:7.0.2-alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6380:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static_volume:
  postgres_data: