# Generated by Django 5.2.1 on 2025-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ожидает одобрения", "Ожидает одобрения"),
                    ("Подтвержден", "Подтвержден"),
                    ("Отклонён", "Отклонён"),
                ],
                default="Ожидает одобрения",
                max_length=17,
            ),
        ),
    ]
