# Generated by Django 5.2.1 on 2025-05-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0003_document_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ожидает одобрения", "Ожидает одобрения"),
                    ("Подтвержден", "Подтвержден"),
                    ("Отклонён", "Отклонён"),
                ],
                default="Ожидает одобрения",
                max_length=17,
            ),
        ),
    ]
