# Generated by Django 5.2.1 on 2025-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0004_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_paid",
            field=models.BooleanField(default=None),
        ),
    ]
