# Generated by Django 5.2.1 on 2025-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documents", "0005_document_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
